name: Deploy

on:
  push:
    branches:
      - main   # sirf merge ke baad chalega
    pull_request:
    branches-ignore:
      - '**'  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        run: echo "🚀 Deploying..."
